In [2]:
import torch 

In [ ]:
torch.manual_seed(0)
n = 150 
p = 1 
X = torch.distributions.Normal(1, 1).sample((n,p)) # n 
true_sigma = 1.0
Xi = X[:, None, :]      # (n, 1, p)
Xj = X[None, :, :]      # (1, n, p)

# Broadcast to (n, n, p)
Xi = Xi.expand(n, n, p)
Xj = Xj.expand(n, n, p)

X_pairs = torch.stack((Xi, Xj), dim=-1).reshape(n*n, 2, p)  # (n^2, 2, p)

# f_of_X will be (n^2,)
f_of_X = torch.tensor([ (x1 @ x2.t()) * (true_sigma ** 2) for x1, x2 in X_pairs])
f_of_X.shape

# first case we will assume no noise y = f(x) + 0
y = f_of_X.clone()
y.shape # (n^2,)

torch.Size([22500])

In [44]:
# we will have p sigmas to predict
sigmas_pred = torch.distributions.normal.Normal(1.0, 0.1).sample((p,1))
sigmas_pred.requires_grad_(True)

learning_rate = 0.001
epochs = 100
losses = []
for epoch in range(epochs): 
    linear_kernel_pred = torch.ones(n**2) # placeholder
    for i in range(n**2):
        x1, x2 = X_pairs[i]
        print(x1)
    
        
    loss = torch.mean((linear_kernel_pred - f_of_X) ** 2)
    losses.append(loss.item())
    loss.backward()
    with torch.no_grad():
        sigmas_pred -= learning_rate * sigmas_pred.grad
        sigmas_pred.grad.zero_()
    if epoch % 10 == 0: 
        print(f"Loss at epoch {epoch} is {loss.item()}")
        print(f"  sigmas_pred = {sigmas_pred.data}")
print(f" Losses over epochs: {losses}")

tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0.1258])
tensor([-0

KeyboardInterrupt: 